"""Traduce al ingles las lineas que escriben las herramientas del kit (registro del Mod Kit en EN).

Las herramientas escriben en espanol; en vez de tocar cada `print`, el Mod Kit pasa cada linea por
`traducir()` cuando el idioma es EN. Cada pareja es (formato espanol, formato ingles) con los mismos
%s/%d/%x en el mismo orden; lo que no casa con ninguna se queda tal cual.

Uso:  python log_en.py    (autocomprobacion)
"""
import re

PAIRS = [
    # roster_build (pulsar JUGAR / Reconstruir ahora)
    ("%s: altura: cadera de las animaciones del donante x%.3f %+.2f", "%s: height: donor animation hips x%.3f %+.2f"),
    ("%s: altura: el moveset del donante ya cuadra (x%.3f %+.2f)", "%s: height: the donor moveset already fits (x%.3f %+.2f)"),
    ("%s (id %d): traje extra %s, modelos por forma %s", "%s (id %d): extra costume %s, models per form %s"),
    ("%s: aviso: modelo_forma %s fuera de 0..%d (modelos_por_traje)", "%s: warning: modelo_forma %s outside 0..%d (modelos_por_traje)"),
    ("%s: aviso: fisica = %r: personaje sin modelos, sin fisica", "%s: warning: fisica = %r: character without models, no physics"),
    ("_roster al dia (%d personajes)", "_roster up to date (%d characters)"),
    ("idiomas del select: usi + %s", "select languages: usi + %s"),
    ("_roster listo: %d personajes, data_cmn %d..%d", "_roster ready: %d characters, data_cmn %d..%d"),
    ("!! este personaje usa el moveset del donante: ya lleva sus capsulas (no hay nada que importar)",
     "!! this character uses the donor's moveset: it already has its capsules (nothing to import)"),
    ("!! %s no tiene #CCM (moveset)", "!! %s has no #CCM (moveset)"),
    ("el moveset no pide ninguna capsula", "the moveset needs no capsule"),
    ("port de Budokai 3: %d capsulas del juego (se quedan tal cual): %s", "Budokai 3 port: %d game capsules (kept as they are): %s"),
    ("capsulas de %s: %d", "capsules of %s: %d"),
    ("!! %s: personaje %r sin modelos en el juego", "!! %s: character %r has no models in the game"),
    ("!! %s: sin modelos", "!! %s: no models"),
    ("!! %s: modelo %s no valido (%s): personaje omitido", "!! %s: model %s is not valid (%s): character skipped"),
    ("capsulas Custom de los IDs %s: sus capsulas cambiaron, vuelven a la lista Normal (copia: capsulas_custom.txt.*.bak)",
     "Custom capsule lists of IDs %s: their capsules changed, back to the Normal list (backup: capsulas_custom.txt.*.bak)"),
    ("el mod no trae imagenes originales en ui/", "the mod has no original images in ui/"),
    ("animaciones %s del donante en %d moveset(s)", "donor animations %s in %d moveset(s)"),
    ("capsulas: las del donante (%s)", "capsules: the donor's (%s)"),
    ("capsula %d: %s (especial)", "capsule %d: %s (special)"),
    ("capsula %d: %s (definitiva)", "capsule %d: %s (ultimate)"),
    ("capsula %d: %s (transformacion forma %d)", "capsule %d: %s (transformation form %d)"),
    ("capsula %d: %s (%s)", "capsule %d: %s (%s)"),
    ("%s: aviso: formas = %d pero %s solo tiene %d", "%s: warning: formas = %d but %s only has %d"),
    ("sin personajes nuevos activos: _roster eliminado", "no active new characters: _roster removed"),
    ("sin personajes nuevos activos", "no active new characters"),
    ("%s: id %d, donante %d (%s), modelos %s, bocas %s, retratos %s, altura %.1f -> escala %.2f",
     "%s: id %d, donor %d (%s), models %s, mouths %s, portraits %s, height %.1f -> scale %.2f"),
    ("aviso: sin vista previa (%s)", "warning: no preview (%s)"),
    ("!! no existe la lista %s", "!! the list %s does not exist"),
    ("icono: el modelo no se pudo renderizar (%s); se usa ui/cara.png", "icon: the model could not be rendered (%s); using ui/cara.png"),
    ("retrato: el modelo no se pudo renderizar (%s); se usa la imagen", "portrait: the model could not be rendered (%s); using the image"),
    ("!! %s pide la plaza %s: %s", "!! %s asks for slot %s: %s"),
    ("sin plaza libre", "no free slot"),
    ("ocupada; usa %s", "taken; uses %s"),
    ("capsula '%s': tipo desconocido (%s)", "capsule '%s': unknown type (%s)"),
    ("!! %s: no quedan IDs libres (maximo %d personajes nuevos)", "!! %s: no free IDs left (at most %d new characters)"),
    ("aviso: data_%s.afs: texturas del select distintas, idioma sin casillas nuevas",
     "warning: data_%s.afs: different select textures, language without new cells"),
    ("aviso: data_%s.afs: sin plantilla para los rotulos, idioma sin casillas nuevas",
     "warning: data_%s.afs: no template for the name banners, language without new cells"),
    ("aviso: data_%s.afs: rotulos en otras texturas, idioma sin casillas nuevas",
     "warning: data_%s.afs: name banners in other textures, language without new cells"),
    ("poses del select propias: IDs %s", "own select poses: IDs %s"),
    ("aviso: poses del select de los donantes (%s)", "warning: select poses from the donors (%s)"),
    ("cara de la barra de vida: %s", "health bar face: %s"),
    ("%d golpes ligados a sus capsulas propias", "%d moves linked to its own capsules"),
    ("no hereda las tecnicas del donante %s", "does not inherit the donor's techniques %s"),
    ("%s: sin cara de la barra de vida (%s)", "%s: no health bar face (%s)"),
    ("modo hiper: animacion y efecto de Budokai 3 (los de %s)", "hyper mode: Budokai 3 animation and effect (%s's)"),
    ("%d formas sin P+K+G en su moveset: transformacion del donante",
     "%d forms without P+K+G in its moveset: donor transformation"),
    ("%s: aviso: voces del donante (%s)", "%s: warning: donor voices (%s)"),
    ("%s: gritos propios (%s, %d huecos)", "%s: own yells (%s, %d slots)"),
    ("%s: aviso: gritos del donante (%s)", "%s: warning: donor yells (%s)"),
    ("aviso: sin injerto del modo hiper (%s)", "warning: no hyper mode graft (%s)"),
    ("aviso: sin transformacion del donante (%s)", "warning: no donor transformation (%s)"),
    ("%s: color del ki %s (%d texturas, %d particulas)", "%s: ki color %s (%d textures, %d particles)"),
    ("%s: color del aura %s (%d texturas)", "%s: aura color %s (%d textures)"),
    ("definitiva con animaciones propias: %d codigos de la cinematica", "ultimate with its own animations: %d cinematic codes"),
    ("tecnicas tras combo (%d): %s", "techniques after combos (%d): %s"),
    ("aviso: sin tecnicas tras combo (%s)", "warning: no techniques after combos (%s)"),
    ("aviso: definitiva con las animaciones del donante (%s)", "warning: ultimate with the donor's animations (%s)"),
    ("%s: aviso: color del ki sin cambiar (%s)", "%s: warning: ki color unchanged (%s)"),
    ("%s: aviso: color del aura sin cambiar (%s)", "%s: warning: aura color unchanged (%s)"),
    ("%s: aura de %s", "%s: aura of %s"),
    ("%s: aviso: aura del donante (%s)", "%s: warning: donor's aura (%s)"),
    ("%s: aviso: altura del donante sin ajustar (%s)", "%s: warning: donor height not adjusted (%s)"),
    ("transformacion del donante: entrada P+K+G del donante (codigos %s)", "donor transformation: donor P+K+G entry (codes %s)"),
    ("transformacion del donante: animaciones %s del donante en %d moveset(s)", "donor transformation: donor animations %s in %d moveset(s)"),
    ("BCM de Infinite World adaptado: %s", "Infinite World BCM adapted: %s"),
    ("voces de Shin Budokai (%s): %d frases propias, %d del donante", "Shin Budokai voices (%s): %d own lines, %d from the donor"),
    ("voces de Infinite World (%s): %d grabaciones", "Infinite World voices (%s): %d recordings"),
    ("altura: cadera de las animaciones del donante x%.3f %+.2f", "height: donor animation hips x%.3f %+.2f"),
    ("mod fuente creado: %s", "source mod created: %s"),
    ("vista previa -> %s", "preview -> %s"),
    ("plaza %d (%s): %s", "slot %d (%s): %s"),
    ("voces del donante", "donor voices"),
    ("sin voz", "no voice"),
    ("personajes nuevos:", "new characters:"),
    # importar
    ("importando %s de %s: %d modelos, donante %d", "importing %s from %s: %d models, donor %d"),
    ("listo: %s (se monta al pulsar JUGAR o Reconstruir ahora)", "done: %s (mounted when you press PLAY or Rebuild now)"),
    ("el donante tiene %d formas: se usan los %d primeros modelos", "the donor has %d forms: the first %d models are used"),
    ("capsula de transformacion: %s (forma %d)", "transformation capsule: %s (form %d)"),
    ("ERROR: no encuentro %r en %s", "ERROR: %r not found in %s"),
    ("ERROR: el conversor de modelos de Heroes (awo_tools/sdbh_model.py) aun no esta listo",
     "ERROR: the Heroes model converter (awo_tools/sdbh_model.py) is not ready yet"),
    ("golpes, combos y camara de %s (%s)", "moves, combos and camera from %s (%s)"),
    ("port de la comunidad: moveset de %s (sustituia al ID %d)", "community port: moveset from %s (it replaced ID %d)"),
    ("voces y gritos de Infinite World: %s", "Infinite World voices and yells: %s"),
    ("capsulas de las tecnicas de SB: nombres oficiales (sb_tecnicas)", "SB technique capsules: official names (sb_tecnicas)"),
    ("aviso: golpes de SB sin portar (%s): se usan los del donante", "warning: SB moves not ported (%s): using the donor's"),
    ("capsulas propias: %d (renombralas en el editor si quieres)", "own capsules: %d (rename them in the editor if you like)"),
    ("aviso: capsulas sin importar (%s)", "warning: capsules not imported (%s)"),
    ("aviso: capsulas de transformacion sin crear (%s)", "warning: transformation capsules not created (%s)"),
    ("aviso: tecnicas de SB sin portar, se usan las del donante (%s)", "warning: SB techniques not ported, using the donor's (%s)"),
    # capsulas / gritos / voces
    ("especial %d (IW %#x) -> capsula %s", "special %d (IW %#x) -> capsule %s"),
    ("modo hiper: su entrada pasa delante de los definitivos (mismos botones)", "hyper mode: its entry goes before the ultimates (same buttons)"),
    ("quitada la entrada de transformarse del moveset (w0 %#x, botones %#x, ki %d, codigo %#x)",
     "removed the transform entry from the moveset (w0 %#x, buttons %#x, ki %d, code %#x)"),
    ("modo hiper: entrada de 'aura burst' de IW convertida (LT/L2)", "hyper mode: IW 'aura burst' entry converted (LT/L2)"),
    ("definitivo -> capsula %d", "ultimate -> capsule %d"),
    ("tabla de voces: %d situaciones propias, %d del donante", "voice table: %d own situations, %d from the donor"),
    ("aviso: sin ffmpeg solo hay frases del banco de combate (no las ATRAC3plus)",
     "warning: without ffmpeg only the combat bank lines are available (not the ATRAC3plus ones)"),
    ("lang_%s: %d huecos, banco %d B (donante %d B), SNR minimo %.1f dB", "lang_%s: %d slots, bank %d B (donor %d B), minimum SNR %.1f dB"),
    ("%d %s %d voces", "%d %s %d voices"),
    # sbport / b1port / sb_tecnicas (importador)
    ("BCM de SB: %d arranques -> %d; quitadas: %s; variantes aura (solo golpes): %d",
     "SB BCM: %d starters -> %d; removed: %s; aura variants (moves only): %d"),
    ("ataques de SB: %d codigos (0x4xx -> 0x2xx, 0x6xx -> 0x3xx); reubicados %s",
     "SB attacks: %d codes (0x4xx -> 0x2xx, 0x6xx -> 0x3xx); relocated %s"),
    ("motor: %d codigos de SB (%s); injertados del donante %d codigos (%d animaciones)",
     "engine: %d SB codes (%s); grafted from the donor %d codes (%d animations)"),
    ("altura: cadera de SB x%.3f %+.2f, del donante x%.3f %+.2f", "height: SB hips x%.3f %+.2f, donor x%.3f %+.2f"),
    ("altura: cadera de B1 x%.3f %+.2f, del donante x%.3f %+.2f", "height: B1 hips x%.3f %+.2f, donor x%.3f %+.2f"),
    ("AMM: %d de SB + %d del donante; huesos %d", "AMM: %d from SB + %d from the donor; bones %d"),
    ("BCM: entradas en los dos %d de %d nativas; solo nativas %s; solo convertidas %s",
     "BCM: entries in both %d of %d native; native only %s; converted only %s"),
    ("forma M%d: el 2.o #BSK redefine %s", "form M%d: the 2nd #BSK redefines %s"),
    ("BCM de SB: %d entradas piden golpes que su BSK no define: quitadas", "SB BCM: %d entries ask for moves its BSK does not define: removed"),
    ("huesos con alias (otra forma): %s", "aliased bones (another form): %s"),
    ("definitivo de la capsula %d -> cinematica del donante 0x25A", "ultimate of capsule %d -> donor cinematic 0x25A"),
    ("el SPX no es el del donante", "the SPX is not the donor's"),
    ("codigos del motor sin definir %s", "undefined engine codes %s"),
    ("codigos bajos fuera de lugar %s", "low codes out of place %s"),
    ("combos sin golpe %s", "combos without a move %s"),
    ("sin rafaga de ki", "no ki blast"),
    ("sin agarre", "no throw"),
    ("sin modo hiper", "no hyper mode"),
    ("entrada de transformacion (la pone roster_build)", "transformation entry (added by roster_build)"),
    ("BCM: del donante %s (cond %#x, codigo %#x)", "BCM: from the donor %s (cond %#x, code %#x)"),
    ("bandera de SB en el sub-bloque %#x", "SB flag in sub-block %#x"),
    ("entrada con valores de SB: %s", "entry with SB values: %s"),
    ("huesos del AMM que no estan en el modelo: %s", "AMM bones not in the model: %s"),
    ("el guion %d empuja %#x y no esta", "script %d pushes %#x and it is missing"),
    ("agarre: falta %#x", "throw: %#x missing"),
    ("ids de linea AP%d que no son 0..n-1 (%#x)", "AP%d line ids that are not 0..n-1 (%#x)"),
    ("HR fuera de rango (%#x)", "HR out of range (%#x)"),
    ("linea de golpe con formato SB (%#x)", "hit line in SB format (%#x)"),
    ("golpes B1: dano x%.2f; %d lineas con guion de B1 -> despide (dano %d)", "B1 moves: damage x%.2f; %d lines with a B1 script -> knockaway (damage %d)"),
    ("esqueleto: sin giro (reposo distinto) %s; posiciones corregidas %s", "skeleton: no rotation (different rest pose) %s; positions fixed %s"),
    ("modo hiper del donante: codigos %s; acometida (SPX 0): %s", "donor hyper mode: codes %s; rush (SPX 0): %s"),
    ("guion: %d codigos del motor injertados del donante (%d animaciones, %d bloques de dano)",
     "script: %d engine codes grafted from the donor (%d animations, %d damage blocks)"),
    ("BCM: tecnica %d con entrada directa %s + E (codigo %#x)", "BCM: technique %d with direct input %s + E (code %#x)"),
    ("BCM: entrada del donante %s (botones %#x, condicion %#x, codigo %#x)", "BCM: donor entry %s (buttons %#x, condition %#x, code %#x)"),
    ("agarre (P+G) del donante: %s", "donor throw (P+G): %s"),
    ("transformacion: P+K+G -> 0x2E0/0x3E0 (bloque B3) con la animacion B1 de %s", "transformation: P+K+G -> 0x2E0/0x3E0 (B3 block) with the B1 animation of %s"),
    ("huesos: %d del modelo B3; de B1 sin hueso en el modelo: %s", "bones: %d from the B3 model; B1 ones without a bone in the model: %s"),
    ("guion %d del donante: codigo %#x (en B1 es otro golpe) -> %#x", "donor script %d: code %#x (another move in B1) -> %#x"),
    ("aviso: sin codigo libre para %#x del guion %d", "warning: no free code for %#x of script %d"),
    ("guion %d del donante: codigo %#x injertado", "donor script %d: code %#x grafted"),
    ("origen: pierna %.2f tobillo %.2f -> correccion escala %.3f, y %+.2f", "source: leg %.2f ankle %.2f -> scale fix %.3f, y %+.2f"),
    ("BSP: %d AST (+%d), %d ASE (+%d), #AME clonados %d+%d, texturas +%d (%d en total)",
     "BSP: %d AST (+%d), %d ASE (+%d), #AME cloned %d+%d, textures +%d (%d in total)"),
    ("capsulas en el BCM: %s; AST %s; ASE %s", "capsules in the BCM: %s; AST %s; ASE %s"),
    ("%s: codigos %#x/%s, capsula provisional %d, BSP %s", "%s: codes %#x/%s, temporary capsule %d, BSP %s"),
    (", golpe con dano %d", ", move with damage %d"),
    ("otros golpes: enlaces c4 de SB sin efecto en el BSP hibrido, quitados: %s", "other moves: SB c4 links without effect in the hybrid BSP, removed: %s"),
    ("%d particulas con textura inexistente", "%d particles with a missing texture"),
    ("el BSP no tiene los mismos hijos que el del donante", "the BSP does not have the same children as the donor's"),
    ("acciones c0 que B3 no conoce: %s", "c0 actions B3 does not know: %s"),
    ("enlaces c4 de golpes del BCM que no estan en el BSP: %s", "c4 links of BCM moves not in the BSP: %s"),
    ("c4 sin destino en codigos que el BCM no lanza (no se ejecutan): %s", "c4 without target in codes the BCM never fires (never run): %s"),
    ("el AMM 2 (victimas de la cinematica) no es el del donante", "AMM 2 (cinematic victims) is not the donor's"),
    ("prueba: utilidades OK (sin la ISO de SB2: no se prueba el BSP)", "test: utilities OK (no SB2 ISO: the BSP is not tested)"),
    ("CON ERRORES", "WITH ERRORS"),
    ("%#x %s: definitivo cinematico del donante (sin BSP propio)", "%#x %s: donor cinematic ultimate (no own BSP)"),
    ("%#x: efectos de SB sin equivalente (se quitan): %s", "%#x: SB effects without an equivalent (removed): %s"),
    ("aviso: %s (SB %#x) no esta en el moveset de A", "warning: %s (SB %#x) is not in A's moveset"),
    ("%s: entrada quitada del BCM (%s)", "%s: entry removed from the BCM (%s)"),
    ("%s: entrada P+K+G+E (modo hiper) -> cinematica del donante %#x/%#x, capsula %d",
     "%s: P+K+G+E entry (hyper mode) -> donor cinematic %#x/%#x, capsule %d"),
    ("%s: codigo %#x -> %#x (zona de especiales)", "%s: code %#x -> %#x (specials range)"),
    ("%s: beam struggle (cond 0x2000 + c0 0x68) y respuesta cond2 0x4003 en %#x/%#x",
     "%s: beam struggle (cond 0x2000 + c0 0x68) and cond2 0x4003 answer at %#x/%#x"),
    ("%s: definitivo en SB -> especial %sE (delante de los de esa direccion)", "%s: ultimate in SB -> special %sE (before the ones with that direction)"),
    ("%s: %d bloques no miden %#x", "%s: %d blocks are not %#x long"),
    ("#ACE con %d nodos alcanzables de %d", "#ACE with %d reachable nodes of %d"),
    ("entrada %#x con beam struggle (0x2000) sin c0 0x68", "entry %#x with beam struggle (0x2000) without c0 0x68"),
    ("textura %d sin DDS valido", "texture %d without a valid DDS"),
    ("hijo %d del BSP del donante cambiado", "child %d of the donor BSP changed"),
    ("el BCM pide el codigo %#x, que no existe", "the BCM asks for code %#x, which does not exist"),
    ("respuesta %#x (cond2 0x4003) sin c0 0x69", "answer %#x (cond2 0x4003) without c0 0x69"),
    ("respuesta %#x sin su entrada con beam struggle", "answer %#x without its beam struggle entry"),
    ("especial %#x sin congelacion 0x64 ... 0x66", "special %#x without freeze 0x64 ... 0x66"),
    ("definitivo %#x antes que la entrada del modo hiper", "ultimate %#x before the hyper mode entry"),
    ("definitivo %#x sin golpe de guion (HR tipo 3) a una ranura del SPX", "ultimate %#x without a script hit (HR type 3) to an SPX slot"),
    ("definitivo %#x -> SPX ranura %d, codigos de la cinematica: %s", "ultimate %#x -> SPX slot %d, cinematic codes: %s"),
    ("%s bloque %d: enlace +%#x al hijo %d, que no es un #ACE", "%s block %d: link +%#x to child %d, which is not an #ACE"),
    ("la cinematica (ranura %d) pide codigos que faltan: %s", "the cinematic (slot %d) asks for missing codes: %s"),
    ("AST %#x: textura %d inexistente", "AST %#x: texture %d missing"),
    ("AMB %d sin %s", "AMB %d without %s"),
    # sdbh_model / b3_gateway
    ("%s: %d huesos, %d texturas", "%s: %d bones, %d textures"),
    ("[X] %s: falta el .esk o el .emb", "[X] %s: the .esk or the .emb is missing"),
    ("[X] %d ventanas: no caben en una IB de 16 bits", "[X] %d windows: they do not fit in a 16-bit IB"),
    ("[X] la plantilla debe ser un #AMB HD descomprimido: %s", "[X] the template must be a decompressed HD #AMB: %s"),
    ("[!] %d ventanas en el AWG0 > %d (maximo nativo): en COMBATE el cuerpo puede desaparecer. Decima la malla de origen.",
     "[!] %d windows in AWG0 > %d (native maximum): in COMBAT the body may disappear. Decimate the source mesh."),
    ("[*] #AZT de la fuente: %d texturas, %d materiales", "[*] source #AZT: %d textures, %d materials"),
    ("[!] huesos sin equivalente en la plantilla (-> raiz):", "[!] bones without an equivalent in the template (-> root):"),
    ("[!] %d materiales > %d draws skinneados: se fusionan los ultimos", "[!] %d materials > %d skinned draws: the last ones are merged"),
    ("[!] %s: sin draw con su material -> draw %d", "[!] %s: no draw with its material -> draw %d"),
    ("[*] huesos por sufijo: %d/%d con equivalente directo", "[*] bones by suffix: %d/%d with a direct equivalent"),
    ("[X] textura %d no es DXT3 %dx%d (no se puede reescribir en sitio)", "[X] texture %d is not DXT3 %dx%d (cannot be rewritten in place)"),
    # texturas
    ("Listo: %d PNG (%d identificados) en %s", "Done: %d PNG (%d identified) in %s"),
    ("Escaneando bins para identificar texturas...", "Scanning bins to identify textures..."),
    ("Texturas indexadas: %d", "Indexed textures: %d"),
    ("Sin --afs: solo conversion (agrupado por WxH).", "No --afs: conversion only (grouped by WxH)."),
    ("%s: fallo al convertir (%s)", "%s: conversion failed (%s)"),
    ("Bin %d: %d texturas -> %s", "Bin %d: %d textures -> %s"),
    ("DONE. Edita los PNG en %s y ejecuta: texture_b3.py build --mod %s", "DONE. Edit the PNGs in %s and run: texture_b3.py build --mod %s"),
    ("Origen (texturas): bin %d -> Destino (slot): bin %d", "Source (textures): bin %d -> Destination (slot): bin %d"),
    ("%d texturas reemplazadas", "%d textures replaced"),
    ("ERROR: el bin %d no es un modelo #AMB (primero %r). Este slot probablemente no tiene modelo/texturas propios.",
     "ERROR: bin %d is not an #AMB model (first %r). This slot probably has no model/textures of its own."),
    ("ERROR: no hay textures_meta.json en %s (ejecuta extract primero)", "ERROR: no textures_meta.json in %s (run extract first)"),
    ("AVISO: la ruta de carpeta contiene caracteres invalidos; usando la automatica: %s", "WARNING: the folder path has invalid characters; using the automatic one: %s"),
    ("ERROR: no se pudo descomprimir bin %d: %s", "ERROR: could not decompress bin %d: %s"),
    ("ERROR: %s. El personaje %d no tiene texturas #AZT propias (modelo parcial o variante que reutiliza las de otro bin).",
     "ERROR: %s. Character %d has no #AZT textures of its own (partial model or variant that reuses another bin's)."),
    ("bin %d: %d texturas, %.1f MB de bitmap; escalado x%d -> %.1f MB", "bin %d: %d textures, %.1f MB of bitmap; upscaled x%d -> %.1f MB"),
    ("extraidas %d texturas a %s", "extracted %d textures to %s"),
    ("ERROR: upscaler no encontrado: %s", "ERROR: upscaler not found: %s"),
    ("ERROR: no hay #AZT en el bin", "ERROR: no #AZT in the bin"),
    ("ERROR: (de momento) solo se soportan bins #AMB", "ERROR: (for now) only #AMB bins are supported"),
    ("ERROR: %dx%d no es potencia de 2 (log2 no valido)", "ERROR: %dx%d is not a power of 2 (invalid log2)"),
    ("verify OK: %d texturas, %d -> %d B", "verify OK: %d textures, %d -> %d B"),
    ("ERROR: AFS no encontrado (%s)", "ERROR: AFS not found (%s)"),
    ("no se encontro index.jsonl en '%s' (no se valida el hash)", "index.jsonl not found in '%s' (hash not checked)"),
    ("ERROR: no existe la carpeta '%s'", "ERROR: folder '%s' does not exist"),
    ("(nombre no valido)", "(invalid name)"),
    (": el nombre no sigue <hash>_<W>x<H>_<sufijo>", ": the name does not follow <hash>_<W>x<H>_<suffix>"),
    (": el hash no existe en el volcado (¿textura equivocada?)", ": the hash is not in the dump (wrong texture?)"),
    (": el volcado da dimensiones invalidas", ": the dump gives invalid dimensions"),
    ("(factor no entero)", "(factor not whole)"),
    ("no contiene .dds/.png", "contains no .dds/.png"),
    # swap
    ("Entrada %d: loc=0x%X size=%d -> nuevo bin %d bytes (delta %+d)", "Entry %d: loc=0x%X size=%d -> new bin %d bytes (delta %+d)"),
    ("usa el bin explicito o 'Nombre:Variante'", "use the explicit bin or 'Name:Variant'"),
    ("Mod generado (override por entrada, bajo peso): %s", "Mod generated (per-entry override, small): %s"),
    ("ERROR: no hay bin que coincida con '%s'", "ERROR: no bin matches '%s'"),
    ("ERROR: no se encontro xbcompress en %s", "ERROR: xbcompress not found in %s"),
    ("ERROR: no se encontro %s", "ERROR: %s not found"),
    ("ERROR: el bin origen no es #AMB (magic %r)", "ERROR: the source bin is not #AMB (magic %r)"),
    ("AVISO: bin comprimido %d > to_read %d del slot %d.", "WARNING: compressed bin %d > to_read %d of slot %d."),
    ("El runtime (mid-insert virtual) autoriza bins mayores:", "The runtime (virtual mid-insert) allows bigger bins:"),
    ("la entrada crece in-place y las posteriores se desplazan.", "the entry grows in place and the following ones shift."),
    ("Padding al to_read virtual %d.", "Padding to virtual to_read %d."),
    ("ERROR: no se pudo descomprimir bin origen: %s", "ERROR: could not decompress the source bin: %s"),
    ("VERIFY: FALLO al descomprimir el override: %s", "VERIFY: FAILED to decompress the override: %s"),
    ("xbcompress no encontrado en %s", "xbcompress not found in %s"),
    ("se requiere --afs (o --describe)", "--afs is required (or --describe)"),
    ("se requiere --to (entrada destino)", "--to is required (destination entry)"),
    ("se requiere --from (entrada) o --bin (archivo)", "--from (entry) or --bin (file) is required"),
    ("AVISO: tipo %s pero el bin no contiene %s (magics=%s)", "WARNING: type %s but the bin does not contain %s (magics=%s)"),
    ("AVISO: bin %d > to_read %d del slot %d -> mid-insert virtual (pad a %d)", "WARNING: bin %d > to_read %d of slot %d -> virtual mid-insert (pad to %d)"),
    # csk / acm
    ("== Attack codes con AP type 1 (ataques reales) ==", "== Attack codes with AP type 1 (real attacks) =="),
    ("total con hitbox: %d", "total with a hitbox: %d"),
    ("HR block %d fuera de rango", "HR block %d out of range"),
    ("attack %#x: sin bloque de animacion", "attack %#x: no animation block"),
    ("(sin AP type 1 -> no es un ataque con hitbox)", "(no AP type 1 -> not an attack with a hitbox)"),
    ("HR %#x fuera de rango, saltado", "HR %#x out of range, skipped"),
    ("attack %#x: sin AP type 1 (no es un ataque con hitbox)", "attack %#x: no AP type 1 (not an attack with a hitbox)"),
    ("NO es #AMB; magics encontrados:", "NOT an #AMB; magics found:"),
    # 2026-10-09: modo hiper / definitiva para todos (IW, B1) y moveset original de IW
    ("sin entrada de modo hiper (P+K+G) en su BCM", "no hyper mode entry (P+K+G) in its moveset"),
    ("sin definitiva en su BCM", "no ultimate in its moveset"),
    ("forma %d: moveset sin #CSK", "form %d: moveset without #CSK"),
    ("forma %d: el codigo %#x del modo hiper no tiene animacion", "form %d: hyper mode code %#x has no animation"),
    ("forma %d: el codigo %#x del definitivo no tiene animacion", "form %d: ultimate code %#x has no animation"),
    ("modo hiper sin comprobar (%s)", "hyper mode not checked (%s)"),
    ("golpes, tecnicas y definitiva de Infinite World (personaje %d de IW)",
     "moves, techniques and ultimate from Infinite World (IW character %d)"),
    ("sin moveset de IW para este modelo: golpes del donante", "no IW moveset for this model: donor moves"),
    ("moveset de IW sin leer (%s): golpes del donante", "IW moveset could not be read (%s): donor moves"),
    ("definitiva del donante (capsula %d del juego, se hereda)", "donor's ultimate (game capsule %d, inherited)"),
    ("definitiva del donante: codigos %s%s, cinematica %d codigos, guion %s",
     "donor's ultimate: codes %s%s, cinematic %d codes, script %s"),
    ("sin codigo libre para el %#x de la definitiva", "no free code for ultimate code %#x"),
    ("voces y gritos de Infinite World: %s", "Infinite World voices and yells: %s"),
    # auditoria 2026-10-09 (lo que sale al usar el Kit)
    ("!! tipo desconocido: %s (especial, definitiva o transformacion)",
     "!! unknown type: %s (valid values: especial, definitiva, transformacion)"),
    ("plantilla del rayo: la de Gohan adulto (el donante no tiene rayo propio)",
     "beam template: Adult Gohan's (the donor has no beam of its own)"),
    ("plantilla de la carga: la de Gohan adulto", "charge template: Adult Gohan's"),
    ("plantilla del destello: la de Gohan adulto", "flash template: Adult Gohan's"),
    ("%#x %s: omitida (%s)", "%#x %s: skipped (%s)"),
    ("%#x %s: AST SB %#x -> %#x = AST %#x del ID %d (tipo %d, dano %d)%s",
     "%#x %s: SB AST %#x -> %#x = AST %#x of ID %d (type %d, damage %d)%s"),
    ("%#x %s: AST SB %#x (tipo %d) -> %#x tipo %d, dano %d, hueso %d, efecto %s",
     "%#x %s: SB AST %#x (type %d) -> %#x type %d, damage %d, bone %d, effect %s"),
    ("ASE SB %#x -> %#x (%s, hueso %d, codigos %s)", "SB ASE %#x -> %#x (%s, bone %d, codes %s)"),
    ("lineas c4 de los ASE renumerados: %d", "c4 lines of the renumbered ASEs: %d"),
    ("%#x: anim %d (%d f) -> tramo %d-%d de la anim %d%s", "%#x: anim %d (%d f) -> span %d-%d of anim %d%s"),
    ("tramo %d-%d de la anim %d", "span %d-%d of anim %d"),
    ("codigo %#x sin sub-bloque en el #CSK", "code %#x has no sub-block in the #CSK"),
    ("codigo %#x: animacion %d del banco %d (solo el propio, 3)", "code %#x: animation %d of bank %d (own only, 3)"),
    ("animacion de origen %d inexistente", "source animation %d does not exist"),
    ("aura %s (entrada %d, %d texturas)", "aura %s (entry %d, %d textures)"),
    ("ki %s (%d texturas, %d particulas)", "ki %s (%d textures, %d particles)"),
    ("capsula %d %s: %s", "capsule %d %s: %s"),
    ("%s es gris: solo se puede cambiar el tono (elige un color)", "%s is grey: only the tone can be changed (pick a color)"),
    ("color desconocido: %r (usa %s, #RRGGBB o un tono 0-359)", "unknown color: %r (use %s, #RRGGBB or a tone 0-359)"),
    ("aura de %r desconocida (ID 0-43 o %s)", "unknown aura %r (ID 0-43 or %s)"),
    ("el BSP no tiene %s", "the BSP has no %s"),
    ("la capsula %d no tiene efectos propios en este personaje", "capsule %d has no own effects on this character"),
    ("el donante no tiene entrada de transformacion (P+K+G)", "the donor has no transformation entry (P+K+G)"),
    ("BSK: %d codigos, %d bloques HR (dano x%.2f)", "BSK: %d codes, %d HR blocks (damage x%.2f)"),
    ("lineas AP7: %s", "AP7 lines: %s"),
    ("codigos que comparten bloque", "codes that share a block"),
    ("animacion %d inexistente (codigo %#x)", "animation %d does not exist (code %#x)"),
    ("combo a codigo bajo", "combo to a low code"),
    ("AP7 clase %d: nativas %d, en los dos (frame) %d, mismo valor %d%s, solo convertidas %d",
     "AP7 class %d: native %d, in both (frame) %d, same value %d%s, converted only %d"),
    ("montaje %d-%d: codigo %d", "build %d-%d: code %d"),
    ("ERROR: ningun PNG editado en %s", "ERROR: no edited PNG in %s"),
    ("Guardado: %s (%d bytes)", "Saved: %s (%d bytes)"),
    ("Guardado: %s", "Saved: %s"),
    ("Uso: python %s", "Usage: python %s"),
    ("%s: aviso: tecnicas propias ilegibles (%s): las del donante", "%s: warning: own techniques unreadable (%s): the donor's"),
    # definitiva de B1 traducida a B3 (b1port)
    ("definitiva de B1 (ranura %d, capsula %s): %d animaciones, %d frames -> %d codigos de la cinematica del donante",
     "B1 ultimate (slot %d, capsule %s): %d animations, %d frames -> %d codes of the donor's cinematic"),
    ("la cinematica del donante es demasiado corta (%d f) para la definitiva de B1 (%d f): se queda la del donante",
     "the donor's cinematic is too short (%d f) for the B1 ultimate (%d f): the donor's stays"),
    ("el donante no tiene cinematica de definitiva: la de B1 no se traduce",
     "the donor has no ultimate cinematic: the B1 one is not translated"),
    ("definitiva del donante: su capsula %d es una de B1 -> %d", "donor's ultimate: its capsule %d is a B1 one -> %d"),
    ("BCM: el especial de las capsulas %s es la definitiva (%d entradas fuera)",
     "BCM: the special of capsules %s is now the ultimate (%d entries removed)"),
    ("definitiva de Budokai 1 traducida: %s (sobre la cinematica de %s)",
     "Budokai 1 ultimate translated: %s (on %s's cinematic)"),
    ("definitiva: %s (la del donante)", "ultimate: %s (the donor's)"),
    ("%s: su animacion de SB en %d codigos de la cinematica del donante", "%s: its SB animation in %d codes of the donor's cinematic"),
    ("el port de la comunidad esta incompleto (sin modo hiper): moveset original de IW",
     "the community port is incomplete (no hyper mode): original IW moveset"),
    ("port de la comunidad sin comprobar (%s)", "community port not checked (%s)"),
]

# Restos frecuentes que aparecen sueltos (notas compuestas en varias partes).
WORDS = [
    ("las del donante", "the donor's"), ("del donante", "from the donor"), ("de los donantes", "from the donors"),
    ("aviso:", "warning:"), ("AVISO:", "WARNING:"), ("especial)", "special)"), ("definitiva)", "ultimate)"),
    ("entry definitiva (", "entry ultimate ("), ("entry modo hiper (", "entry hyper mode ("),
    ("entry agarre (", "entry throw ("),
]

_SPEC = re.compile(r"%[-+ #0]*\d*(?:\.\d+)?[sdrxXf]")


def _compile(es):
    out, pos = [], 0
    for m in _SPEC.finditer(es):
        out.append(re.escape(es[pos:m.start()]))
        out.append("(.+?)" if m.group() in ("%s", "%r") else r"(\S+?)")
        pos = m.end()
    tail = re.escape(es[pos:])
    return re.compile("".join(out) + tail + ("$" if out and pos == len(es) else ""))


def _template(en):
    n = [0]

    def rep(_m):
        n[0] += 1
        return "\\g<%d>" % n[0]
    return _SPEC.sub(rep, en.replace("\\", "\\\\"))


_RULES = sorted(((_compile(es), _template(en), len(es)) for es, en in PAIRS), key=lambda r: -r[2])


def traducir_linea(line):
    for rx, tpl, _ in _RULES:      # todas, de la mas larga a la mas corta: hay notas anidadas
        m = rx.search(line)
        if m:
            line = line[:m.start()] + m.expand(tpl) + line[m.end():]
    for es, en in WORDS:
        line = line.replace(es, en)
    return line


def traducir(text):
    """Texto de varias lineas (lo que llega de una herramienta) -> ingles, linea a linea."""
    return "".join(traducir_linea(ln) for ln in text.splitlines(True))


if __name__ == "__main__":
    casos = {
        "   cut_android19: capsulas: las del donante (Dr.GERO)\n": "   cut_android19: capsules: the donor's (Dr.GERO)\n",
        "   cut_burter: voces del donante": "   cut_burter: donor voices",
        "_roster listo: 9 personajes, data_cmn 3990..4060": "_roster ready: 9 characters, data_cmn 3990..4060",
        "   port_gohan_futuro: capsula 614: Burning Attack (especial)": "   port_gohan_futuro: capsule 614: Burning Attack (special)",
        "   port_gohan_futuro: capsula 616: Super Saiyan (transformacion forma 1)":
            "   port_gohan_futuro: capsule 616: Super Saiyan (transformation form 1)",
        "   cut_dodoria: gritos propios (b1:14, 55 huecos)": "   cut_dodoria: own yells (b1:14, 55 slots)",
        "+ Android 19: id 31, donante 32 (Dr.GERO), modelos [3990, 3991], bocas [3992], retratos [3993, 3994], altura 14.9 -> escala 1.12":
            "+ Android 19: id 31, donor 32 (Dr.GERO), models [3990, 3991], mouths [3992], portraits [3993, 3994], height 14.9 -> scale 1.12",
        "   cut_guldo: altura: cadera de las animaciones del donante x0.358 +0.44":
            "   cut_guldo: height: donor animation hips x0.358 +0.44",
        "listo: imp_x (se monta al pulsar JUGAR o Reconstruir ahora)": "done: imp_x (mounted when you press PLAY or Rebuild now)",
        "C:\\ruta\\sin cambios": "C:\\ruta\\sin cambios",
    }
    for es, en in casos.items():
        got = traducir(es)
        assert got == en, (es, got)
    print("log_en.py: autocomprobacion OK (%d frases)" % len(PAIRS))
